config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    after_create :inscription_email

    validates :stripe_customer_id, presence: true
    
    belongs_to :user
    belongs_to :event
    
    private
    
    def inscription_email
        UserMailer.event_inscription_email(self.user, self.event).deliver_now
    end
end

app/models/event.rb
class Event < ApplicationRecord
    validates :start_date, presence: true, numericality: { greater_than_or_equal_to: Time.now.to_i }
    validates :duration, presence: true, if: :mult_5_and_positive?
    validates :title, presence: true, length: { minimum: 5, maximum: 140 }
    validates :description, presence: true, length: { minimum: 20, maximum: 1000 }
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
    validates :location, presence: true
    
    has_many :attendances
    has_many :users, through: :attendances
    belongs_to :organizer, class_name: 'User'
    
    private
    
    def mult_5_and_positive?
        return true if self.duration % 5 == 0 && self.duration > 0
        false
    end
end

app/models/user.rb
class User < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
    
    after_create :welcome_send
    
    #validates :first_name, presence: true
    #validates :last_name, presence: true
    #validates :encrypted_password, presence: true, length: { minimum: 5, maximum: 15 }
    validates :email, presence: true, uniqueness: true, format: {with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/, message: 'email adress please'}
    
    has_many :attendances
    has_many :events, through: :attendances
    has_many :organised_events, foreign_key: 'organizer', class_name: 'Event'
    
    private
    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_event, only: %i[ show edit update destroy ]
    
    # GET /events or /events.json
    def index
        @events = Event.all
    end

    # GET /events/1 or /events/1.json
    def show
    end

    # GET /events/new
    def new
        @event = Event.new
    end

    # GET /events/1/edit
    def edit
    end

    # POST /events or /events.json
    def create
        @event = Event.new(event_params)
        respond_to do |format|
            if @event.save
                format.html { redirect_to @event, notice: "Event was successfully created." }
                format.json { render :show, status: :created, location: @event }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @event.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /events/1 or /events/1.json
    def update
        respond_to do |format|
            if @event.update(event_params)
                format.html { redirect_to @event, notice: "Event was successfully updated." }
                format.json { render :show, status: :ok, location: @event }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @event.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /events/1 or /events/1.json
    def destroy
        @event.destroy
        respond_to do |format|
            format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
        @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
        params.fetch(:event, {})
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :auth_user?

    def show
        @user = current_user
    end

    private
    
    def auth_user?
        unless User.find(params[:id]) == current_user
            redirect_to events_path, alert: "T'es pas au bon endroit !"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
    <% if event.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
        <% event.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
    </ul>
    </div>
<% end %>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>
<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Hello, guy !</h1>
            <p>Bienvenu sur le site My Fucking Eventbrite !</p>
        </div>
      </div>

      <div class="container">
      <% @events.each do |event| %>
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
            
                <h2><%= event.title %></h2>
                <p><%= event.duration %></p>
                <p><%= event.location %></p>
                <p><a class="btn btn-secondary" href="#" role="button"><%= link_to "Show", event %>View details &raquo;</a></p>
            </div>
        </div>
    <p id="notice"><%= notice %></p>
                <p><%= link_to "Edit", edit_event_path(event) %></p>
                <p><%= link_to "Destroy", event, method: :delete, data: { confirm: "Are you sure?" } %></p>
        <% end %>
<br>
<%= link_to "New Event", new_event_path %>

app/views/events/new.html.erb
<h1>Nouvel évènement</h1>

<form > 
  <%= form_for @event, url: {action: "create"} do |f| %>
  <br>
    Title
    <div class="form_group"><%= f.text_field :title %></div>
    Description : 
    <div class="form_group"><%= f.text_area :description %></div>
    Prix : 
    <div class="form_group"><%= f.number_field :price %></div>
    Durée :
    <div class="form_group"><%= f.number_field :duration %></div>
    Location : 
    <div class="form_group"><%= f.text_field :title %></div>

    <div class="form_group"><%= f.submit "Create", class: "btn btn-default btn-primary"%></div>
    <% end %>
</form>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My fucking Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>

  <body>

    <!-- Navbar -->
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">The Fucking Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="Navbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%=events_path%>">Accueil <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_event_path %>">Add Event</a>
      </li>
      <li class="nav-item">
      <div class="dropdown">
            <% if user_signed_in? %>
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mon Profil</a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="<%=user_path(current_user)%>">Détails profil</a>              
                <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-confirm="Êtes-vous sûr ?" data-method="DELETE" >Disconnect</a></p>   
              </div>
            <% else %>
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Se connecter/S'inscrire</a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="/users/sign_up">Sign Up</a>              
                <a class="dropdown-item" href="/users/sign_in">Sign In</a>              
              </div>
            <% end %>
      </div>
      </li>
    </ul>
  </div>
</nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/static_pages/event.html.erb
<h1>StaticPages#event</h1>
<p>Find me in app/views/static_pages/event.html.erb</p>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/users/index.html.erb
<h1>User home</h1>

<% @users.each do |user| %> 
    <%= user.first_name %>
    <a href="<%= user_path(user.id) %>" class="card-link btn btn-dark">Show</a>
    <br>
<% end %>  

app/views/users/show.html.erb
<h1>Mon profil</h1>

<div class="container">
    <div class="card-body">
        <ul class="list-group">

            <li class="list-group-item">
                Email :<p><%=current_user.email%></p> 
            </li>

            <li class="list-group-item">
                First name : <p><%=current_user.first_name%></p> 
            </li>

            <li class="list-group-item">
                Last name : <p><%=current_user.last_name%></p> 
            </li>

            <li class="list-group-item">
                Description : <p><%=current_user.description%></p> 
            </li>
        </ul>
    </div>

</div>

<div class="container">
    <ul class="list-group">
        <li class="">
            <%=button_to 'Changer mon mot de passe', new_user_password_path(current_user.id), method: 'get', class: 'btn btn-danger'%>
        </li>

        <li class="">
            <a href=<%=edit_user_registration_path%> class="btn btn-danger">Modifier mes infos</a>
        </li>

        <li class="">
            <a href="#" class="btn btn-danger">Modifier ma description</a>
        </li>

        <li class="">
            <a href="#" class="btn btn-danger">Modifier mon prénom</a>
        </li>

        <li class="">
            <a href="#" class="btn btn-danger">Modifier mon nom</a>
        </li>
    </ul>
</div>